
from datetime import date

# UNIQUE QUOTES
quotes = [
    "Believe in yourself a little more every single day.",
    "You are becoming the person you once prayed to be.",
    "Small steps are still steps—keep moving.",
    "Consistency will always beat intensity.",
    "You are capable of absolutely anything you commit to.",
    "Progress is progress, no matter how slow.",
    "You don’t need to be perfect, you just need to start.",
    "One good decision today can change your entire life.",
    "Don’t let your doubts destroy your potential.",
    "You are stronger than yesterday.",
    "Make yourself proud today.",
    "Great things take time—stay patient and persistent.",
    "Every morning is a gift; treat it like one.",
    "Be brave enough to try, even if you’re scared.",
    "Your dreams deserve your effort.",
    "Show up for yourself even when it’s hard.",
    "Discipline is choosing what you want most over what you want now.",
    "You have survived 100% of your hardest days.",
    "Success begins with one simple step.",
    "Never underestimate your ability to rise again.",
    "The life you desire is built through daily habits.",
    "You don’t need to rush—just don’t stop.",
    "Believe in the timing of your life.",
    "A little effort each day creates massive change.",
    "You are rewriting your story with every choice.",
    "Stay consistent even on the boring days.",
    "You owe yourself the love you give others.",
    "If it scares you, it’s probably worth trying.",
    "Nothing changes if nothing changes.",
    "Keep going; the world needs what you have.",
    "Your future self is cheering for you.",
    "Trust yourself—you’ve got this.",
    "Every accomplishment starts with a decision to try.",
    "It’s not luck—it’s hard work.",
    "Stop doubting. Start doing.",
    "One day, all your patience will make sense.",
    "Don’t let temporary emotions make permanent decisions.",
    "You are allowed to take up space.",
    "Make today better than yesterday.",
    "Your potential is limitless.",
    "Be the reason someone believes in goodness.",
    "The best investment is you.",
    "Even slow progress is a win.",
    "You are not behind—you are building.",
    "Trust your journey.",
    "Work hard in silence; let success make the noise.",
    "You are capable of rewriting your destiny.",
    "Small improvements eventually create big results.",
    "Let your actions reflect your ambitions.",
    "Fight for the life you want.",
    "Today is a fresh start.",
    "Become obsessed with your growth.",
    "Challenges shape champions.",
    "Let go of what you can’t control.",
    "The best is yet to come.",
    "Dream boldly, act fearlessly.",
    "Never apologize for wanting more for yourself.",
    "You didn’t come this far to quit now.",
    "Comfort zones never create legends.",
    "Your mindset determines your success.",
    "Breathe. Reset. Continue.",
    "You matter. Your goals matter.",
    "Don’t compete—become better than you were.",
    "Give yourself permission to start over.",
    "Work until your efforts inspire others.",
    "One moment of courage can change everything.",
    "Be disciplined enough to win.",
    "No dream is too big when your effort matches it.",
    "Growth isn’t always visible, but it’s happening.",
    "Stay loyal to your goals.",
    "Bet on yourself.",
    "You are capable of extraordinary things.",
    "Failure is not the opposite of success; it’s part of it.",
    "Do something today that moves you forward.",
    "Your value doesn’t decrease based on someone’s opinion.",
    "Keep showing up, even tired.",
    "Believe in the person you are becoming.",
    "The only competition is your older self.",
    "Work on yourself, for yourself.",
    "Turn your excuses into action.",
    "You deserve a life you are proud of.",
    "Embrace the uncomfortable—it means you are growing.",
    "Let your dreams be bigger than your fears.",
    "One struggle at a time. One victory at a time.",
    "You are not defined by your mistakes.",
    "Step out of your comfort zone.",
    "Your comeback will be stronger than your setback.",
    "You can do far more than you imagine.",
    "Stay patient—everything is aligning for you.",
    "Choose courage over comfort.",
    "Don’t give up on the person you’re becoming.",
    "You are your only limit.",
    "Your dreams are valid.",
    "Every day is a new chance to improve.",
    "Protect your peace.",
    "Make your vision clearer than your excuses.",
    "You are on the right path.",
    "Do it scared. Do it unsure. Just do it.",
    "Show up even when no one claps.",
    "Be the energy you want to receive.",
    "Master the art of showing up.",
    "Your hard work will pay off.",
    "You are worthy of every good thing.",
    "You are building a stronger version of yourself.",
    "Believe in the power of consistency.",
    "You’re allowed to grow beyond who you once were.",
    "The next chapter of your life will be beautiful.",
    "Don’t wait for motivation—create discipline.",
    "Think bigger. Act bolder.",
    "What you do today matters more than you think.",
    "You were made for greatness.",
    "Keep trying—your breakthrough is near.",
    "Be proud of the small wins too.",
    "Your energy introduces you before you speak.",
    "Don’t dim your light for anyone.",
    "Your effort will never betray you.",
    "You are unstoppable when you believe in yourself.",
    "Do it with passion or not at all.",
    "Keep learning. Keep rising.",
    "You are capable of mastering anything.",
    "Take control of your story.",
    "Don’t limit your dreams.",
    "One day at a time is enough.",
    "You have the power to change your life.",
    "Believe in new beginnings.",
    "Greatness requires sacrifices.",
    "Act like the person you want to become.",
    "Don’t fear failure—fear not trying.",
    "Choose progress over perfection.",
    "Make every day purposeful.",
    "Success begins with your mindset.",
    "Strength grows in silence.",
    "Your potential is bigger than your fears.",
    "Keep moving—your blessings are coming.",
    "You belong here.",
    "No matter what, don’t give up on yourself.",
    "You are building a masterpiece—your life.",
    "Turn your pressure into power.",
    "Stay brave. Stay bold.",
    "Chase goals, not approval.",
    "Great achievements start with small habits.",
    "Your persistence will be rewarded.",
    "Be your own motivation.",
    "Doubt kills more dreams than failure ever will.",
    "You were born to rise.",
    "Speak kindly to yourself.",
    "You are enough.",
    "Keep going even when you don’t feel like it.",
    "You are learning every day.",
    "Be hungry for growth.",
    "One day you’ll be glad you never gave up.",
    "Everything is possible with effort.",
    "Your potential is waiting for you.",
    "Show up for your dreams.",
    "Never stop dreaming.",
    "Fight for your vision.",
    "Take the risk—your future self will thank you.",
    "You can become anything you desire.",
    "Keep walking; the path will reveal itself.",
    "Every day is a chance to rise higher.",
    "You are capable of achieving greatness.",
    "Transform your challenges into strength.",
    "The best version of you is loading.",
    "You get better every time you try.",
    "You deserve success.",
    "Don’t let your fears guide your decisions.",
    "Do it with confidence.",
    "Your efforts matter—even the unseen ones.",
    "Nobody can stop you except you.",
    "Keep your focus on the end goal.",
    "A better life starts with better choices.",
    "You have unlimited potential.",
    "Be proud of how far you’ve come.",
    "Trust the process.",
    "You are becoming unstoppable.",
    "Stay strong; things will get better.",
    "Take action—don’t wait for perfect conditions.",
    "You are exactly where you need to be.",
    "Turn your wounds into wisdom.",
    "You are not your past.",
    "Refuse to give up.",
    "Keep working; success is near.",
    "Build good habits—they build your future.",
    "You have purpose.",
    "Choose hope every day.",
    "You’re closer than you think.",
    "Progress requires patience.",
    "Every step forward counts.",
    "You are evolving beautifully.",
    "Show yourself some love.",
    "Trust the power within you.",
    "Be fearless in pursuit of what sets your soul on fire.",
    "Don’t let comfort stop your growth.",
    "You deserve to shine.",
    "Keep trying—success loves persistence.",
    "Your dreams are worth fighting for.",
    "Focus on what you can control.",
    "Believe in your possibilities.",
    "You are your greatest asset.",
    "Don’t lose sight of your goals.",
    "Consistency compounds.",
    "Rest, but don’t quit.",
    "Think positive, act positive.",
    "Today is a good day to grow.",
    "Push your limits.",
    "Keep choosing yourself.",
    "Your hard work will take you far.",
    "Don’t be afraid to shine.",
    "You create your reality.",
    "Your success story is unfolding.",
    "Rise every time you fall.",
    "The world needs your magic.",
    "Don’t wait—create.",
    "Your goals are worth the effort.",
    "Courage creates opportunities.",
    "Never underestimate yourself.",
    "Your perseverance is your superpower.",
    "You’re capable of extraordinary change.",
    "Turn your can’ts into cans.",
    "One small win today, one giant win tomorrow.",
    "You can start again.",
    "Hope is powerful—use it.",
    "You are getting closer every day.",
    "Work hard and trust yourself.",
    "Train your mind to see possibilities.",
    "You are worthy of big dreams.",
    "Go the extra mile—it’s never crowded.",
    "You are destined for amazing things.",
    "Don’t look back—you’re not going that way.",
    "Your dreams need your dedication.",
    "You are making progress even on slow days.",
    "Stay focused on what matters.",
    "Believe in your inner strength.",
    "Break your limits.",
    "You deserve a fresh start.",
    "Keep your heart strong.",
    "Work hard in silence.",
    "You can overcome anything.",
    "Build the habits that build your future.",
    "Believe you can succeed.",
    "You are worthy of growth.",
    "Keep fighting for your dreams.",
    "Every day is a chance to get better.",
    "You are unstoppable when you decide to be.",
    "Keep focusing on your goals.",
    "You are capable of greatness.",
    "Choose discipline over distraction.",
    "You have the strength to overcome.",
    "Be proud of your journey.",
    "Every sunrise is a new beginning.",
    "You’re becoming a better version of yourself.",
    "Create the life you want.",
    "Stay grateful, stay growing.",
    "Believe in the person you’re becoming.",
    "Your growth is your responsibility.",
    "Become the person you admire.",
    "A little courage goes a long way.",
    "You are transforming beautifully.",
    "Let your actions reflect your goals.",
    "Don’t just wish—work.",
    "Your determination makes you powerful.",
    "You deserve happiness.",
    "Focus on the solution, not the problem.",
    "Keep growing silently.",
    "You will rise again, stronger.",
    "You’re allowed to be proud of yourself.",
    "Chase your dreams relentlessly.",
    "Your journey is unique—own it.",
    "You are enough as you are.",
    "Don’t stop believing in yourself.",
    "Your habits shape your identity.",
    "Keep walking toward your goals.",
    "You’re learning more than you think.",
    "You already have what it takes.",
    "Your patience will be rewarded.",
    "Trust the timing of your growth.",
    "Your work is paying off.",
    "Believe in new possibilities.",
    "You are becoming unstoppable.",
    "Take one brave step today.",
    "Your courage can move mountains.",
    "You are breaking barriers.",
    "Don’t let fear win.",
    "You are worthy of success.",
    "Keep pushing forward.",
    "Each step brings you closer.",
    "You’re becoming someone powerful.",
    "Your dedication defines you.",
    "Don’t shrink—grow.",
    "Stay committed, even in silence.",
    "Your dreams are waiting for you.",
    "Your hard work will shine.",
    "You are destined for more.",
    "You have so much potential.",
    "Don’t stop until you’re proud.",
    "Your courage is inspiring.",
    "You’re capable of rewriting your story.",
    "Believe in your transformation.",
    "You deserve to win.",
    "Make today meaningful.",
    "The world needs your strength.",
    "You’re getting stronger every day.",
    "Let your progress motivate you.",
    "You can overcome any obstacle.",
    "Success requires effort—keep going.",
    "You are becoming who you were meant to be.",
    "Keep believing in better days.",
    "Your dreams deserve your commitment.",
    "Every day is an opportunity to grow.",
    "You’re too strong to quit.",
    "You are evolving beautifully.",
    "You deserve a beautiful life.",
    "Your journey is worth it.",
    "Believe in yourself loudly.",
    "You’re not alone; keep going.",
    "Your heart knows the way.",
    "You can handle anything life throws at you.",
    "You’re getting closer to the life you want.",
    "Stay hungry for growth.",
    "Your future is bright.",
    "You’re becoming unstoppable.",
    "Let your progress speak for itself.",
    "You are capable of moving mountains.",
    "Stay focused; your dreams need you.",
    "Your spirit is powerful.",
    "You always rise.",
    "Your effort is never wasted.",
    "You are full of potential.",
    "Keep working on yourself.",
    "You are enough and always will be.",
    "Push yourself—you can do it.",
    "Keep striving for greatness.",
    "You are a work in progress and that’s okay.",
    "Your life is becoming beautiful.",
    "Trust your ability to grow.",
    "You’re building something amazing.",
    "Don’t stop believing in your vision.",
    "You can achieve anything you commit to.",
    "Stay consistent and you will win.",
    "You’re capable of reaching your highest potential.",
    "Your daily choices shape your destiny.",
    "Your courage is greater than your fear.",
    "You are unstoppable—believe it.",
    "Keep improving one day at a time.",
    "Believe in your inner power.",
    "You are shaping your own future.",
    "Strength grows through storms.",
    "You have what it takes to succeed.",
    "Your determination will open doors.",
    "Every day brings new opportunities.",
    "You are doing better than you think.",
    "Don’t give up—big things take time.",
    "Your persistence makes you powerful.",
    "You’re becoming the best version of yourself.",
    "Keep showing up for your dreams.",
    "You’re almost there—don’t stop.",
    "Your hard work will pay off beautifully.",
    "You are capable of unbelievable growth.",
    "Stay focused—your success is coming.",
    "You are courageous and resilient.",
    "Your future self will thank you.",
    "You’re on your way to greatness.",
    "Every step forward is victory.",
    "You are worthy of every good thing coming your way.",
    "Today is your day—go make it amazing."

]
# --- GET TODAY'S DATE ---
today = date.today()
d = today.day
m = today.month
y = today.year

# --- DAYS IN EACH MONTH ---
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

# cumulative days
cumulative = [0]
total = 0
for x in days_in_month[:-1]:
    total += x
    cumulative.append(total)

# --- CALCULATE DAY OF YEAR ---
day_number = cumulative[m-1] + d

# --- PICK QUOTE ---
index = (day_number - 1) % 365
quote = quotes[index]

# --- OUTPUT ---
print("\n----- DAILY MOTIVATION -----")
print("Date:", today.strftime("%d %B %Y"))
print("Day:", today.strftime("%A"))
print(f"\nIt is day {day_number} of the year!\n")
print("Your Quote of the Day:")
print(quote)
print("-----------------------------\n")